export const subjectTopics = {
  Türkçe: [
    "Sözcükte Anlam",
    "Cümlede Anlam",
    "Paragraf",
    "Dil Bilgisi",
    "Edebiyat",
  ],
  Matematik: [
    "Sayılar",
    "Denklemler",
    "Fonksiyonlar",
    "Geometri",
    "İstatistik",
    "Üçgenler",
    "Dörtgenler",
    "Çember",
    "Analitik Geometri",
    "Katı Cisimler",
  ],
  Fizik: ["Mekanik", "Termodinamik", "Optik", "Elektrik", "Modern Fizik"],
  Kimya: ["Atom Yapısı", "Bağlar", "Asit-Baz", "Organik Kimya", "Elektrokimya"],
  Biyoloji: [
    "Hücre",
    "Kalıtım",
    "Ekosistem",
    "İnsan Anatomisi",
    "Bitki Biyolojisi",
  ],
  Tarih: ["İlk Çağ", "Orta Çağ", "Yeni Çağ", "Yakın Çağ", "Türk Tarihi"],
  Coğrafya: [
    "Fiziki Coğrafya",
    "Beşeri Coğrafya",
    "Türkiye Coğrafyası",
    "Harita Bilgisi",
    "Çevre Sorunları",
  ],
  Felsefe: [
    "Antik Felsefe",
    "Bilgi Felsefesi",
    "Ahlak Felsefesi",
    "Siyaset Felsefesi",
    "İslam Felsefesi",
    "Modern Felsefe",
    "Mantık",
  ],
  Din: [
    "Kelam",
    "Tefsir",
    "Hadis",
    "Fıkıh",
    "İslam Tarihi",
    "Dinler Tarihi",
    "Ahlak",
  ],
};
