export const subjectTopics = {
  Türkçe: [
    "Sözcükte Anlam",
    "Cümlede Anlam",
    "Paragraf",
    "Dil Bilgisi",
    "Edebiyat",
  ],
  Matematik: [
    "Sayılar",
    "Denklemler",
    "Fonksiyonlar",
    "Geometri",
    "İstatistik",
  ],
  "Fen Bilimleri": ["Fizik", "Kimya", "Biyoloji"],
  "Sosyal Bilimler": ["Tarih", "Coğrafya", "Felsefe", "Din"],
  Fizik: ["Mekanik", "Termodinamik", "Optik", "Elektrik", "Modern Fizik"],
  Kimya: ["Atom Yapısı", "Bağlar", "Asit-Baz", "Organik Kimya", "Elektrokimya"],
  Biyoloji: [
    "Hücre",
    "Kalıtım",
    "Ekosistem",
    "İnsan Anatomisi",
    "Bitki Biyolojisi",
  ],
  Edebiyat: [
    "Nazım",
    "Nesir",
    "Dil Bilgisi",
    "Edebiyat Tarihi",
    "Anlam Bilgisi",
  ],
  Tarih: ["İlk Çağ", "Orta Çağ", "Yeni Çağ", "Yakın Çağ", "Türk Tarihi"],
  Coğrafya: [
    "Fiziki Coğrafya",
    "Beşeri Coğrafya",
    "Türkiye Coğrafyası",
    "Harita Bilgisi",
    "Çevre Sorunları",
  ],
  Geometri: [
    "Üçgenler",
    "Dörtgenler",
    "Çember",
    "Analitik Geometri",
    "Katı Cisimler",
  ],
};
