import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={` ${GeistSans.className} font-geist-sans text-sm antialiased`}
    >
      <body className={``}>
        <Providers
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
        >
          {children}
        </Providers>
      </body>
    </html>
  );
}
