export const tytTurkceTopics = [
  `Anlatım Bozuklukları`,
  "Cümle Türleri",
  "Cümlede Anlam",
  "Cümlenin Öğeleri",
  "Edat-Bağlaç-Ünlem",
  "Fiilde Çatı",
  "Fiilimsiler",
  "Fiiller",
  "İsimler",
  "Noktalama İşaretleri",
  "Paragraf",
  "Ses Bilgisi",
  "Sıfatlar",
  "Sözcükte Anlam",
  "Sözcükte Yapı",
  "Yazım Kuralları",
  "Zamirler",
  "Zarflar",
  "Paragrafın Yapısı",
  "Paragrafın Ana Düşüncesi",
  "Paragrafta Yardımcı Düşünceler",
  "Sözcük Türleri",
  "Tamlamalar",
  "Ekler",
  "Karma Dil Bilgisi",
  "İletişim Dil ve Kültür",
];

export const tytTarihTopics = [
  "Tarih ve Zaman",
  "İnsanlığın İlk Dönemleri",
  "Ortaçağ’da Dünya",
  "İlk ve Orta Çağlarda Türk Dünyası",
  "İslam Medeniyetinin Doğuşu",
  "İlk Türk İslam Devletleri",
  "Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi",
  "Beylikten Devlete Osmanlı Siyaseti(1300-1453)",
  "Dünya Gücü Osmanlı Devleti (1453-1600)",
  "Yeni Çağ Avrupa Tarihi",
  "Yakın Çağ Avrupa Tarihi",
  "Osmanlı Devletinde Arayış Yılları",
  "18. Yüzyılda Değişim ve Diplomasi",
  "En Uzun Yüzyıl",
  "Osmanlı Kültür ve Medeniyeti",
  "20. Yüzyılda Osmanlı Devleti",
  "I. Dünya Savaşı",
  "Mondros Ateşkesi, İşgaller ve Cemiyetler",
  "Kurtuluş Savaşına Hazırlık Dönemi",
  "I. TBMM Dönemi",
  "Kurtuluş Savaşı ve Antlaşmalar",
  "II. TBMM Dönemi ve Çok Partili Hayata Geçiş",
  "Türk İnkılabı",
  "Atatürk İlkeleri",
  "Atatürk Dönemi Türk Dış Politikası",
];

export const tytCografyaTopics = [
  "Doğa ve İnsan",
  "Dünya’nın Şekli ve Hareketleri",
  "Coğrafi Konum",
  "Harita Bilgisi",
  "Atmosfer ve Sıcaklık",
  "İklimler",
  "Basınç ve Rüzgarlar",
  "Nem, Yağış ve Buharlaşma",
  "İç Kuvvetler / Dış Kuvvetler",
  "Su – Toprak ve Bitkiler",
  "Nüfus",
  "Göç",
  "Yerleşme",
  "Türkiye’nin Yer Şekilleri",
  "Ekonomik Faaliyetler",
  "Bölgeler",
  "Uluslararası Ulaşım Hatları",
  "Çevre ve Toplum",
  "Doğal Afetler",
];

export const tytMatematikTopics = [
  "Temel Kavramlar",
  "Sayı Basamakları",
  "Bölme ve Bölünebilme",
  "EBOB – EKOK",
  "Rasyonel Sayılar",
  "Basit Eşitsizlikler",
  "Mutlak Değer",
  "Üslü Sayılar",
  "Köklü Sayılar",
  "Çarpanlara Ayırma",
  "Oran Orantı",
  "Denklem Çözme",
  "Problemler",
  "Sayı Problemleri",
  "Kesir Problemleri",
  "Yaş Problemleri",
  "Hareket Hız Problemleri",
  "İşçi Emek Problemleri",
  "Yüzde Problemleri",
  "Kar Zarar Problemleri",
  "Karışım Problemleri",
  "Grafik Problemleri",
  "Rutin Olmayan Problemleri",
  "Kümeler – Kartezyen Çarpım",
  "Mantık",
  "Fonskiyonlar",
  "Polinomlar",
  "2.Dereceden Denklemler",
  "Permütasyon ve Kombinasyon",
  "Olasılık",
  "Veri – İstatistik",
];

export const tytGeometriTopics = [
  "Temel Kavramlar",
  "Doğruda Açılar",
  "Üçgende Açılar",
  "Özel Üçgenler",
  "Dik Üçgen",
  "İkizkenar Üçgen",
  "Eşkenar Üçgen",
  "Açıortay",
  "Kenarortay",
  "Eşlik ve Benzerlik",
  "Üçgende Alan",
  "Üçgende Benzerlik",
  "Açı Kenar Bağıntıları",
  "Çokgenler",
  "Özel Dörtgenler",
  "Dörtgenler",
  "Deltoid",
  "Paralelkenar",
  "Eşkenar Dörtgen",
  "Dikdörtgen",
  "Kare",
  "Yamuk",
  "Çember ve Daire",
  "Çemberde Açı",
  "Çemberde Uzun",
  "Dairede Çevre ve Alan",
  "Analitik Geometri",
  "Noktanın Analitiği",
  "Doğrunun Analitiği",
  "Dönüşüm Geometrisi",
  "Analitik Geometri",
  "Katı Cisimler",
  "Prizmalar",
  "Küp",
  "Silindir",
  "Piramit",
  "Koni",
  "Küre",
  "Çemberin Analitiği",
];

export const tytFizikTopics = [
  "Fizik Bilimine Giriş",
  "Madde ve Özellikleri",
  "Sıvıların Kaldırma Kuvveti",
  "Basınç",
  "Isı, Sıcaklık ve Genleşme",
  "Hareket ve Kuvvet",
  "Dinamik",
  "İş, Güç ve Enerji",
  "Elektrik",
  "Manyetizma",
  "Dalgalar",
  "Optik",
];

export const tytKimyaTopics = [
  "Kimya Bilimi",
  "Atom ve Periyodik Sistem",
  "Kimyasal Türler Arası Etkileşimler",
  "Maddenin Halleri",
  "Doğa ve Kimya",
  "Kimyanın Temel Kanunları",
  "Kimyasal Hesaplamalar",
  "Karışımlar",
  "Asit, Baz ve Tuz",
  "Kimya Her Yerde",
];

export const tytBiyolojiTopics = [
  "Canlıların Ortak Özellikleri",
  "Canlıların Temel Bileşenleri",
  "Hücre ve Organelleri",
  "Hücre Zarından Madde Geçişi",
  "Canlıların Sınıflandırılması",
  "Mitoz ve Eşeysiz Üreme",
  "Mayoz ve Eşeyli Üreme",
  "Kalıtım",
  "Ekosistem Ekolojisi",
  "Güncel Çevre Sorunları",
];

export const tytFelsefeTopics = [
  "Felsefe’nin Konusu",
  "Bilgi Felsefesi",
  "Varlık Felsefesi",
  "Ahlak Felsefesi",
  "Sanat Felsefesi",
  "Din Felsefesi",
  "Siyaset Felsefesi",
  "Bilim Felsefesi",
  "İlk Çağ Felsefesi",
  "2. Yüzyıl ve 15. Yüzyıl Felsefeleri",
  "15. Yüzyıl ve 17. Yüzyıl Felsefeleri",
  "18. Yüzyıl ve 19. Yüzyıl Felsefeleri",
  "20. Yüzyıl Felsefesi",
];

export const tytDinTopics = [
  "Bilgi ve İnanç",
  "İslam ve İbadet",
  "Ahlak ve Değerler",
  "Allah İnsan İlişkisi",
  "Hz. Muhammed (S.A.V.)",
  "Vahiy ve Akıl",
  "İslam Düşüncesinde Yorumlar, Mezhepler",
  "Din, Kültür ve Medeniyet",
  "İslam ve Bilim, Estetik, Barış",
  "Yaşayan Dinler",
];

export const topics = {
  tyt: {
    Türkçe: tytTurkceTopics,
    Tarih: tytTarihTopics,
    Coğrafya: tytCografyaTopics,
    Felsefe: tytFelsefeTopics,
    "Din Kültürü": tytDinTopics,
    Matematik: tytMatematikTopics,
    Geometri: tytGeometriTopics,
    Fizik: tytFizikTopics,
    Kimya: tytKimyaTopics,
    Biyoloji: tytBiyolojiTopics,
  },
};
